### ISSUE TITLE
Console spam Not enough random bot accounts available, need # more!!

### ISSUE THREAD

**Issue by rogerc66** [liyunfan1223/mod-playerbots#13]
Console spam Not enough random bot accounts available even random account is more than 500.
it's related with the setting below looks like , how many more accounts needed is less than the number devided by 10.
AiPlayerbot.MaxRandomBots = 400
Trying to increase the number will result need more number of bot respectively.

I have no idea if it's db corruption or setting problem. the msgs stuck the bot log in and there will no bots online.

**Comment by rogerc66** [comment]
> `AiPlayerbot.RandomBotAccountCount = 200` ?

either 200 or higher will have the same issue

**Comment by rogerc66** [comment]
> to me everything looks normal, maybe you need to reinstall the database. I am not sure!

Thank you for your info, my serverr was fine few days ago, no idea why this start happening, I will try to play around with db see if I could figure it out, might be something to do with npcbot, I have both playerbot and npcbot merged.

**Comment by rogerc66** [comment]
I have deleted a few newly created characters and everything back to normal, strange.

**Comment by liyunfan1223** [comment]
Previously there was a probability of failure when creating robot accounts and roles. This was caused by asynchronous database operations. Now rewrite it in https://github.com/liyunfan1223/mod-playerbots/commit/8c9ab0e42833e03b9644777a5b1cd33855e845ee, synchronize the database state by sleeping. (still not the best way but it works)

If anyone encounter similar problem, first comfirm that Random Bot Account Count greater than 10 times MaxRandomBots and not exceed 1000. Then set `AiPlayerbot.DeleteRandomBotAccounts = 1` in config and restart server. Reset it to 0 once accounts an characters are correctly created.

**Comment by BRNKR** [comment]
> Previously there was a probability of failure when creating robot accounts and roles. This was caused by asynchronous database operations. Now rewrite it in [8c9ab0e](https://github.com/liyunfan1223/mod-playerbots/commit/8c9ab0e42833e03b9644777a5b1cd33855e845ee), synchronize the database state by sleeping. (still not the best way but it works)
> 
> If anyone encounter similar problem, first comfirm that RandomBotAccountCount greater than one-tenth of MaxRandomBots and not exceed 1000. Then set `AiPlayerbot.DeleteRandomBotAccounts = 1` in config and restart server. Reset it to 0 once accounts an characters are correctly created.

on first install my worldserver exec created the databases and showed me that error too. i have not changed anything on the config. with DeleteRandomBotAccounts it was fixed after reinitializing the characters. but still looks buggy to me
