### ISSUE TITLE
About 500-600 errors when compiling

### ISSUE THREAD

**Issue by dlsmain** [liyunfan1223/mod-playerbots#133]
I keep getting about 500-600 errors when I try to compile on visual studio after doing the CMAKE process

1)copy from git hub https://github.com/liyunfan1223/azerothcore-wotlk to azerothcore
2)into modules I copy https://github.com/liyunfan1223/mod-playerbots
3)CMAKE I build it in C:/Build
4)Configure
5)TOOLS_BUILD ALL
6)Module_MOD-Playerbots (static)
7)configure again
No errors
8)Generate
9)Open Project 
10)RELWITHDBINFO and X64
11) clean ALL_BUILD
12) build ALL_BUILD
13)???
ton of errors and I don't get the worldserver.exe. I was able to get it working without playerbots earlier but I'm not sure what I'm doing wrong now.

**Comment by noisiver** [comment]
It would help knowing what the errors are. I get an absolute ton of warnings when I compile using this module but it still succeeds. You should include at least something printed or it's impossible to determine what your issue is.

**Comment by evrydayjunglist** [comment]
I only get these 2 warnings during compilation:

Warning	C4834	discarding return value of function with [[nodiscard]] attribute	modules	...\modules\mod-playerbots\src\PlayerbotFactory.cpp	701		

Warning	LNK4006	"protected: unsigned int __cdecl RotateAroundTheCenterPointAction::FindNearestWaypoint(void)" (?FindNearestWaypoint@RotateAroundTheCenterPointAction@@IEAAIXZ) already defined in RaidUlduarActions.obj; second definition ignored	modules	...\modules\RaidNaxxActions.obj	1		

I'm using Windows 10
MySql 8.2.0
Boost 1.78
OpenSSL 3.0.13
CMake 3.29.0 rc4
Visual Studio 17 2022

I assume you're using @liyunfan1223's fork of the core... not sure what else could be different.

**Comment by noisiver** [comment]
Windows doesn't produce the same amount of warnings as Linux. Linux covers more by default so we're talking hundreds upon hundreds of warnings - which also results in it recompiling at least 40% of the code whenever you update because it's checking all those warnings again. Warnings != errors though so I'm curious how they could get 500-600 errors.

They did say they're using the fork but not that they were actually using the correct branch of that fork. The only thing I can see producing a lot of errors is not using the correct branch. Helping people in the AzerothCore discord server I have seen a few that somehow use the master branch instead of the Playerbot branch.

**Comment by liyunfan1223** [comment]
Check CI https://github.com/liyunfan1223/mod-playerbots/actions.
