### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#15]
When a bot is invited to a party, it is possible to use the **summon** command and the bot will appear at your side.

My suggestion would be to add a verification at the time of the party, and if the bot is far away it (bot) will automatically use command the **summon**, what do you think?

I believe this would be a very good solution for the moment.

**Comment by garfieldz90** [comment]
I think now is like really player, it would be better they know how to get your side would be more like human player! I think no need to automatic summon to your side.

**Comment by Dreathean** [comment]
> I think now is like really player, it would be better they know how to get your side would be more like human player! I think no need to automatic summon to your side.

Conversely, that sounds exhausting and a major waste of time to me personally. Maybe it could be a config option though so people can choose whether or not the bots can be summoned or are automatically summoned to you? That way both types of players can be satisfied.

As it stands, if there was no method to automatically summon them to you like NPCBots, then it would be terribly challenging getting a dungeon or raid together quickly. In fact as far as I'm aware there is no mass summon to summon all bots in your party/raid, I think that would be a great addition so that you don't have to individually whisper 39 bots.

**Comment by garfieldz90** [comment]
try this
/p summon

**Comment by garfieldz90** [comment]
> > I think now is like really player, it would be better they know how to get your side would be more like human player! I think no need to automatic summon to your side.
> 
> Conversely, that sounds exhausting and a major waste of time to me personally. Maybe it could be a config option though so people can choose whether or not the bots can be summoned or are automatically summoned to you? That way both types of players can be satisfied.
> 
> As it stands, if there was no method to automatically summon them to you like NPCBots, then it would be terribly challenging getting a dungeon or raid together quickly. In fact as far as I'm aware there is no mass summon to summon all bots in your party/raid, I think that would be a great addition so that you don't have to individually whisper 39 bots.

try
/p summon

**Comment by Dreathean** [comment]
Ah! That's awesome. Thank you for that

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/ced051b16c62ee6bea81198959a155882955cbc7
