### ISSUE TITLE
Worldserver crashes after 1-4 kills in BG while leveling

### ISSUE THREAD

**Issue by Grakazela** [liyunfan1223/mod-playerbots#181]
when doing bg's at level 10-19 worldserver crashes after a few kills have been aquired, higher xp scale values will result in faster crashes (1 kill at 40x xp, 3-4 at 1x xp)

**To Reproduce**
1. join bg
2. kill 3-4 bots, or watch your bots kill theres
3. worldserver stops existing

worldserver log shows nothing at time of crash

**Comment by Dreathean** [comment]
Thanks for posting! So this will also happen with just the bots killing each other - not necessarily just you killing bots?

I have to think this is a recent issue, as when I tested all the battlegrounds a while back I never experiencing any crashing in WSG, AB, or AV. I was only testing in 50-59 bracket however; if you get a chance can you see if this issue persists in a different bracket ie 50-59?

Otherwise I will test when I can but it'll be at least a week until then.

The BG XP rate, especially being a base worldserver config option, having any impact on crashing though is baffling.

**Comment by Dreathean** [comment]
Just saw that Revision stated in the discord that he does not currently have this issue, I wonder if there's another module you're using that could be impacting this?

**Comment by Grakazela** [comment]
module 'honour guard' seems to have been the culprit, i axed it, reran and where golden
