### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by Regrad** [liyunfan1223/mod-playerbots#216]
The repository has not been updated for two weeks. Has this project been abandoned?

**Comment by Dreathean** [comment]
Two weeks is not a particularly long time, Liyunfan is probably either on vacation, super busy with work, or otherwise taking a well deserved break. Of course, I can't rule out what you're saying either but I think it's too soon to say, and he has been gone for periods of time like this before for the aforementioned reasons.

**Comment by Regrad** [comment]
I hope you're right, he's our hero.

**Comment by liyunfan1223** [comment]
I've been busy with some work recently. If you have any ideas or contributions, feel free to propose them. I'd be happy to participate in interesting discussions and projects.

By the way, I've only maintained module code as a player's interest before, and I hope to find meaningful community collaborations. Perhaps it's just a joke, but my point is, when you participate as a contributor, you shouldn't consider other contributors as heroes.
