### ISSUE TITLE
@fuzzdeveloper: BGJoinAction::shouldJoinBg() is unreachable 

### ISSUE THREAD

**Issue by brian8544** [liyunfan1223/mod-playerbots#258]
@brian8544 hey I was just looking through these changes (whenever I update my server I like to have a quick look over what's changed) and I noticed that:
- that the code you've added to BGJoinAction::shouldJoinBg() is unreachable (both code blocks are immediately after a return statement)
- the noLag variable added to FreeBGJoinAction::shouldJoinBg() is unused

Those changes wont introduce problems but won't function as you were likely intending, I do however notice you've changed one of the if statements in BGJoinAction::shouldJoinBg() from:
if (!(hasPlayers || hasBots))
to:
if (!hasPlayers && !(isArena))

That will have an impact (one I'm not sure was intentional) and will have one regardless of the enablePrototypePerformanceDiff setting (it also renders the hasBots variable unused which is partially why I'm wondering if you intended to do this).

All changes mentioned can be found in BattleGroundJoinAction.cpp here:
https://github.com/liyunfan1223/mod-playerbots/pull/243/commits/3879b5116e344469b33d60e05bb7ad05a27cfe7f#diff-4009d1913f93054e322a12b0dadcfb719e16186e4a73d61bf5e2bcd969320653

_Originally posted by @fuzzdeveloper in https://github.com/liyunfan1223/mod-playerbots/pull/243#issuecomment-2148884551_

**Comment by fuzzdeveloper** [comment]
@brian8544 So I took a look through the [mangosbot code](https://github.com/celguar/mangosbot-bots/blob/f01ec095fc6a19946cf12016eda340f9a9f4cf00/playerbot/strategy/actions/BattleGroundJoinAction.cpp#L353) related to this myself and I _think_ you can implement the change by reverting much of it and adding a simple check like this:
```
    if (sPlayerbotAIConfig->enablePrototypePerformanceDiff && !hasPlayers && !noLag)
        return false;
```
So change looks like this (new on right):
![bgda-diff](https://github.com/liyunfan1223/mod-playerbots/assets/50162646/52e5a58b-8e64-47ea-8269-80d590c956e3)

You can probably implement the change to FreeBGJoinAction::shouldJoinBg() by adding the same if statement (the version in mangosbot also has other arena based checks but I believe those are redundant).

**Comment by brian8544** [comment]
This morning I was using the GitHub app, it seems my response and thanks for checking out the code yourself didn't come through, sorry for that!

![image](https://github.com/liyunfan1223/mod-playerbots/assets/7340774/37608180-a07d-4211-aa96-5795b9e21306)
[Unrelated, but keeping this image as a reference]


I modified the code, it was an oversight, it should now be conform Celguar's code:
https://github.com/brian8544/mod-playerbots/commit/3c9634c7d7c532aee40e17be5d5385807b0b3259

This week, i'll check out more of my mistakes, but feel free to make a PR if I did it wrong again, still learning. :D

**Comment by fuzzdeveloper** [comment]
> I modified the code, it was an oversight, it should now be conform Celguar's code: [brian8544@3c9634c](https://github.com/brian8544/mod-playerbots/commit/3c9634c7d7c532aee40e17be5d5385807b0b3259)

Ok that still doesn't look right right because these 2 if statements you've added will cause new behavior regardless of the enablePrototypePerformanceDiff config setting:
```
    if (!hasPlayers && !noLag)
        return false;

    if (botAI->HasRealPlayerMaster())
        return false;
```
I also noticed that you also removed this entirely:
```
    if (!(hasPlayers || hasBots))
        return false;
```
Unless that second if statement you added is a working replacement for the one you removed, I'd remove it and re-add the old one (because it doesn't seem like it's even related to performance stuff you're migrating over - otherwise it'd be checking the noLag variable).

The first if statement (with the noLag check) is the only if statement in the mangosbot code you need to add in, but it needs to be re-written such that it respects the enablePrototypePerformanceDiff setting, which is why I re-wrote it like this (in my post above):
```
    if (sPlayerbotAIConfig->enablePrototypePerformanceDiff && !hasPlayers && !noLag)
        return false;
```
That (and the line which sets the noLag variable) should be the only changes needed to this method to get same performance related behavior as what is in mangosbot (the new logic will basically prevent bots being added to a battleground when enablePrototypePerformanceDiff is enabled AND no real players are in the game AND the server's lagging - I should also note that it won't make any difference unless randomBotAutoJoinBG setting is enabled, which is the same as in mangosbot).

Here's a bit more context of what that would look like:
```
bool BGJoinAction::shouldJoinBg(BattlegroundQueueTypeId queueTypeId, BattlegroundBracketId bracketId)
{
    // check if bot should join (queue has real players)
    BattlegroundTypeId bgTypeId = BattlegroundMgr::BGTemplateId(queueTypeId);
    Battleground* bg = sBattlegroundMgr->GetBattlegroundTemplate(bgTypeId);
    if (!bg)
        return false;

    bool isArena = false;
    bool isRated = false;

    ArenaType type = ArenaType(BattlegroundMgr::BGArenaType(queueTypeId));
    if (type != ARENA_TYPE_NONE)
        isArena = true;

    bool hasPlayers = (sRandomPlayerbotMgr->BgPlayers[queueTypeId][bracketId][TEAM_ALLIANCE] + sRandomPlayerbotMgr->BgPlayers[queueTypeId][bracketId][TEAM_HORDE]) > 0;
    bool hasBots = (sRandomPlayerbotMgr->BgBots[queueTypeId][bracketId][TEAM_ALLIANCE] + sRandomPlayerbotMgr->BgBots[queueTypeId][bracketId][TEAM_HORDE]) >= bg->GetMinPlayersPerTeam();
    bool noLag = sWorldUpdateTime.GetAverageUpdateTime() < (sRandomPlayerbotMgr->GetPlayers().empty() ? sPlayerbotAIConfig->diffEmpty : sPlayerbotAIConfig->diffWithPlayer) * 1.1;

    if (!sPlayerbotAIConfig->randomBotAutoJoinBG && !hasPlayers)
        return false;

    if (!(hasPlayers || hasBots))
        return false;

    if (sPlayerbotAIConfig->enablePrototypePerformanceDiff && !hasPlayers && !noLag)
        return false;

    uint32 BracketSize = bg->GetMaxPlayersPerTeam() * 2;
    uint32 TeamSize = bg->GetMaxPlayersPerTeam();

----------------snip----------------

```
