### ISSUE TITLE
[Suggestion] Future Implementation Idea for "Permanent" Playerbots

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#28]
With the current implementation, all Playerbots have their gear and inventory periodically wiped and replaced. This is subjective, but personally while I feel this method is okay and likely necessary for the level up process, I believe this is a major issue when it comes to the level cap and raiding as it is impossible to achieve true progression with a raid team of bots.

I think it would be a significant addition to enable a feature where once Playerbots hit level cap (whether the level cap is set to 60, 70, or 80) they no longer initialize/replace their gear. For their inventory that should be okay to replace as needed. This will allow both a seamless level curve for the bots with their current randomize function and enable players to enjoy raid progression with both players and bots starting raiding with just rares/greens and working their way up to epic gear.

**Comment by garfieldz90** [comment]
> With the current implementation, all Playerbots have their gear and inventory periodically wiped and replaced. This is subjective, but personally while I feel this method is okay and likely necessary for the level up process, I believe this is a major issue when it comes to the level cap and raiding as it is impossible to achieve true progression with a raid team of bots.
> 
> I think it would be a significant addition to enable a feature where once Playerbots hit level cap (whether the level cap is set to 60, 70, or 80) they no longer initialize/replace their gear. For their inventory that should be okay to replace as needed. This will allow both a seamless level curve for the bots with their current randomize function and enable players to enjoy raid progression with both players and bots starting raiding with just rares/greens and working their way up to epic gear.

Maybe add a choice in configure file like, playerbot.initialize = 1(default:1), if this on,bot will keep init they gear otherwise never init gear, i hope they will build gear by themselves. Event = 0, if they reach like 10,20, 30…, they gear still poor, system will randome init nice gear to bot inventory,they will determine which is good, if you gave a good equipment than randome equipment, they still pick and wear your that would be good!

**Comment by liyunfan1223** [comment]
The existing solution is that you can create new characters under your own account, and let the bot system control these characters through the command `.playerbot add {CHARNAME}` (this works for characters on the same account or within the same guild). Since initialization never happens on these self-created characters, you can trade them for gear, items, and persist them.

Another solution to this is to use a combination of `.playerbot bot addclass {CLASSNAME}` and `.playerbot bot init=epic *`, so that players can quickly get a lot of bots to help them in raids, but the problem is that the equipment of these bots are too strong and will be reset at any time.

I think the problem is actually that for a multiplayer instance (say 40-man), players don't have the energy to create that many characters, learn spells, talents, etc. They need a preset template to initialize these characters, use these initialized characters to enter the raid, and continuously improve the equipment of these characters. But once the initialized template is too strong or can be reset at any time, players cannot experience the fun of developing.

This is a design issue, I have some ideas such as based on the player's gearscore and raid progress when doing the bot initialization. We can further discuss what the best solution is.

**Comment by Dreathean** [comment]
> The existing solution is that you can create new characters under your own account, and let the bot system control these characters through the command `.playerbot add {CHARNAME}` (this works for characters on the same account or within the same guild). Since initialization never happens on these self-created characters, you can trade them for gear, items, and persist them.
> 

This sounds like a good solution, it could be tedious manually creating 39 playerbots but certainly doable. Would it still randomly select the talent path and choosing tank/dps/healer? And is there a command to force a playerbot to a specific spec and role?

> I think the problem is actually that for a multiplayer instance (say 40-man), players don't have the energy to create that many characters, learn spells, talents, etc. They need a preset template to initialize these characters, use these initialized characters to enter the raid, and continuously improve the equipment of these characters. But once the initialized template is too strong or can be reset at any time, players cannot experience the fun of developing.
> 
This makes it sound like the playerbot system wouldn't determine it's own spec/talents/etc for manually created playerbots? Or am I misinterpreting this? 

While I would plan on starting the bots at low level and progress from the beginning, for those looking to just start at lvl 60 (or 70, 80) but wanting to quickly add playerbots, maybe it would be feasible to add configurable options to have playerbots spawn for example at lvl 60 and players can select either "init green" or "init rare" or "init epic" if they want them to spawn with all greens, or rares, or epics depending on what they are looking to do.

> This is a design issue, I have some ideas such as based on the player's gearscore and raid progress when doing the bot initialization. We can further discuss what the best solution is.
>
That is certainly another option though it would also would not feel like the same level of developing characters if you aren't directly gearing the playerbots.

On a side note, I am realizing that my plan of starting at low level with 40 playerbots that do not init/periodically randomize level-appropriate gear falls apart if the playerbots are unable to go into and complete dungeons on their own to gear themselves since I can only reasonably gear up 4 other bots alongside me leveling up. This probably warrants an entirely different discussion, but do you think it is feasible in the future for Playerbots to decide to group up among themselves and do a dungeon all by themselves? I guess that would be a nightmarishly massive project though as you would have to code objectives and directions for basically every dungeon so that is likely impossible.

As it stands, with self-created playerbots then they would effectively not gear up well except for the ones you run dungeons with. I think what we discussed before where playerbots continue to init/add randomized gear while leveling but then stop at level cap (whatever level cap is set to in worldserver.conf) thouh they will of course continue to replace their inventory. This way there shouldn't be any issues for leveling playerbots and then once you hit level cap you can progress raids with them and gear them up at that stage via your progression.

**Comment by liyunfan1223** [comment]
Got it, at present, the relatively simple solution is to stop the equipment initialization of random bots above a certain level and add commands to specify bot talent. I will add a configuration option to control this later. I'll think again about the more follow-up features you mentioned.

**Comment by Dreathean** [comment]
That would definitely be a great addition, thank you so much!

**Comment by liyunfan1223** [comment]
https://github.com/liyunfan1223/mod-playerbots/commit/be13e0e189e5fda47f53bb1a0c697db219d8677c

Two optional configurations are introduced here, setting `AiPlayerbot.EquipmentPersistence = 1` and `AiPlayerbot.EquipmentPersistenceLevel = 80` to make the bot's equipment persistent after level 80.

**Comment by Dreathean** [comment]
That is awesome! I did not expect you to add it so quickly, thank you for another great addition!
