### ISSUE TITLE
Server does not spawn bots after update

### ISSUE THREAD

**Issue by DeewaTT91** [liyunfan1223/mod-playerbots#295]
**Describe the bug**
There are no bots being loaded into the server.

**Commit hash**
The hash of the current commit.

**To Reproduce**
Update the server
Compile
Run

**Expected behavior**
It should spawn a number of bots.

**Screenshots**
![image](https://github.com/liyunfan1223/mod-playerbots/assets/121842068/ff4cc609-41ea-4ba2-930d-99b3f358f5b5)

**Desktop (please complete the following information):**
Debian

**Additional context**
It has worked right before the update.

**Comment by qyh214** [comment]
confirm

**Comment by Dreathean** [comment]
Wonder if it was due to this commit on the main AC, it was just recently updated to Liyunfan's fork - https://github.com/liyunfan1223/azerothcore-wotlk/commit/0a8175ef037732aa25a908687a2c3a019ba5eb55 and he just rolled it back https://github.com/liyunfan1223/azerothcore-wotlk/commit/2a2e2ec445f03544eeb85e336114c5511e50fdab, can you check and see if this issue is resolved with this rollback?

**Comment by DeewaTT91** [comment]
I roll back by running update again, right? If so, this didnt fix it.

**Comment by qyh214** [comment]
> I roll back by running update again, right? If so, this didnt fix it.

check char db , check characters.at_login  should 0 not 1

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/e839581649da9596e0979cbe9f17cf1a1ed90660 fixes it <3

**Comment by DeewaTT91** [comment]
yup, its working again

**Comment by liyunfan1223** [comment]
Thank you @Kitzunu! It should be alright now https://github.com/liyunfan1223/azerothcore-wotlk/commit/223ec63ba509062896b4f4a799c471e81255033d. 

If the database is modified by the wrong version, @qyh214 provided the right way to fix, thanks!
