### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#3]
Hello!!

If you want to bring some Celguar update to this module, remember that this module received the latest Celguar update at https://github.com/celguar/mangosbot-bots/tree/1837718aa01d97f5e71477d48a164aaf089a40ee
Not sure if you knew this so I'm just commenting.

Thank you very much, your work is very good!

**Comment by liyunfan1223** [comment]
Thank you for the information! 

While at the moment, the first thing to do is to make this mod playable and more stable, it seems interesting to port more features from this latest version. Of course, porting code from different cores requires more works, which is also an unavoidable problem.

The best way seems to be to select a few of the interesting features to port instead of trying to merge all the latest updates. If you have more suggestions, such as the addition of specific features, welcome to communicate with me.
