### ISSUE TITLE
Alliance Dranei Shaman stuck on Azuremyst isle

### ISSUE THREAD

**Issue by parkesto** [liyunfan1223/mod-playerbots#357]
**Describe the bug**
Alliance Dranei Shaman stuck @ Level 5, cannot seem to get off Azuremyst isle. I am assuming they are stuck on some kind of class quest as the Paladin Dranei can get out no problems.

**To Reproduce**
Literally just let them do their thing!

**Expected behavior**
Level beyond 5 and leave Azuremyst isle...

**Comment by noisiver** [comment]
There is an area in the Draenei starting area that they can get stuck at. I can't get there right now because I have expansion set to classic, but there are a bunch of blood elves in that area and a tall but fairly narrow "mountain" right before them. I found many times the bots stand on one side of this "mountain" and remain there until the blood elf they're targeting is dead. I just deleted the spawn last time I noticed it.

Go to the bot in question to see where they are, maybe this is the reason.

**Comment by liyunfan1223** [comment]
It will automatically teleport to a suitable area at some intervals.

**Comment by parkesto** [comment]
It does not, and will not, teleport them anywhere. I have bots that have organically levelled 1-70+ now and there are dozens of level 5-7 shamans just sitting on Azuremyst doing nothing.

**Comment by liyunfan1223** [comment]
Okay, that does seem odd. Could you try manually typing`.playerbot rndbot teleport` in the console to see if it works for them? It would be best if you could upload a screenshot to show where they are stuck.
