### ISSUE TITLE
Flag carriers in WSG will hide & not fight back

### ISSUE THREAD

**Issue by Dohtt** [liyunfan1223/mod-playerbots#424]
When a bot is carrying the flag in WSG and reaches their side of the map while their flag is gone, they will hide in the flag room, but not fight back when attacked.

Commit Hash
46c877d

1. Go to WSG
2. Let both teams grab the flags
3. Let the bots reach their respective sides of the map
4. Attack the flag carrier who won't fight back (tested with warlock ranged)

**Expected behavior**
The Flag Carrier should also try to protect themselves.

**Comment by fuzzdeveloper** [comment]
Yeah the bots in BG's (and in general) either move to objectives or fight, never both, usually combat takes priority and movement to objectives stops completely whenever bot is in combat, but there's a big exception made for flag carriers where they've obviously been set to run to objectives and ignore combat (as they'd never cap flag if they took every fight).

I'll see what happens if I allow FC to take fights when when they've taken enemy flag back to their base and they cant cap (only in the area of the flag, and only until their own flag is returned), looks like it'll be possible from what I can see.

FYI I'm also experimenting with having bots move to objectives AND fight at same time, because I have to for vehicles in IOC (because the driver ends up stuck in combat indefinitely for some reason) though I'm not sure whether I can expand it to bots in general because its a bit glitchy (and obviously not something melee classes could really do at all).

**Comment by fuzzdeveloper** [comment]
Fixed in https://github.com/liyunfan1223/mod-playerbots/pull/447

Took me so many hours to do this one I'm actually a bit embarrassed by it - suffice to say the "flag carriers must **always** be passive" behavior was enforced in several different ways:
- you've got several checks for flag-carrier state in BGTactics which force the bot to ignore in-combat state
- checks for FC state in 3 AttackXXXAction classes which force the bot to ignore enemies
- a check for FC state in the PlayerHasFlag trigger which, when active, forces bot to prioritise movement buffing spells (the ones that wont make it drop the flag) as well as hammer away at BGTactics::moveToObjective/selectObjective (to the detriment of doing anything else)

It wouldn't be so bad if the FC state was checked in a consistent manner (so I could find this stuff) but OF COURSE NOT, we have:
- `bot->HasAura(BG_WS_SPELL_WARSONG_FLAG) || bot->HasAura(BG_WS_SPELL_SILVERWING_FLAG` fair enough, check for the aura you get when carrying flag
- `bot->HasAura(23333) || bot->HasAura(23335)` yeah that's intuitive for sure, constants are for pussies! Just store the meaning of those numbers in your head!
- `bot->GetGUID() == bg->GetFlagPickerGUID(TEAM_ALLIANCE)` by the way if you think this checks if an **alliance** bot has the flag, you're wrong! TEAM_ALLIANCE is indicates the faction of the _flag_ you see! (this counter-intuitive detail is documented nowhere)

Happy hunting for me! It was also the most frustrating thing I've had to test so far, if the bots could screw up a test they would find a way (ie: enemy FC _always_ choosing to run past the GY that all my sides bots were stuck at because their movement was disabled). The enemy team also seemed to pursue every possible distraction rather than grab the damn flag, ie: grabbing every one of the stupid buffs, mounting/dismounting several times when they're about to run into my base anyway (mounting being so messed up in BG's right now was certainly not helping). Me holding their flag in midair with .gm fly? What better excuse for a gathering of every damn bot underneath me! (even though I had gm-mode on and was so high up I could barely see them until I came down wondering what was taking so long, I hovered above my own flag in subsequent tests)

Anyway that's my whinge over, have fun! :-)
