### ISSUE TITLE
Frost Mage aggressive water elemental

### ISSUE THREAD

**Issue by Grimfeather** [liyunfan1223/mod-playerbots#444]
**Describe the bug**
Frost mage bots now summon water elementals
https://github.com/liyunfan1223/mod-playerbots/commit/b36521a353448595a5523a02096cd6bd2610950b

the problem is that the stance they are using for their water elemental pet is 'aggressive'.
it attacks everything in sight. not a good thing for party play inside dungeons.

**Commit hash**
AzerothCore rev. c3be0fa2a8b4 2024-08-05 01:22:16 +0800 (Playerbot branch) (Win64, Release, Static) (worldserver-daemon)

**To Reproduce**
1. party with frost mage bot that is high enough level to cast water elemental.
2. wait for the mage to cast the elemental during combat.
3. watch the elemental attack different packs of mobs

**Expected behavior**
defensive or passive.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by Mr-Deadbeat** [comment]
is it a bot with a water elemental that is a permanent pet ? in that case i can understand the frustration but if it's a timed summoned pet they do not have any controls and vanishes after a short while need to plan ahead if you get a mage / deathknight with those types of pets and do pulls around corners and other tricks

only permanent pets have controls so you can set them to passive or defensive my frost mage has a permanent water elemental so going to test just to be sure he is currently spec'd as Arcane due to testing Naxx yesterday was a huge dissapointment btw bots do not know all the fights :(

**Comment by Grimfeather** [comment]
hopefully https://github.com/liyunfan1223/mod-playerbots/commit/2a5b7dcb610048b209e6b3dd8c91b3cbe906b9b3 fixed it.
I'll have to try it and see.

It's the timed summoned pet yes. But it does have controls. When I control the mage myself I can set it to defensive or passive.

Your suggestion is not always possible. Like in BRD towards the emperor, the huge room with a lot of packs where you need to get the 2 torches to light the braziers. It's super frustrating when the mage's water elemental keeps pulling more and more and more.

**Comment by Grimfeather** [comment]
This problem seems to be fixed.
