### ISSUE TITLE
Playerbots initiate trade in Bramblebade Ravine

### ISSUE THREAD

**Issue by AldebaraanMKII** [liyunfan1223/mod-playerbots#698]
**Describe the bug**
Playerbots initiate trade in Bramblebade Ravine when killing mobs there.
This happens when you invite random bots from Camp Narache. When inviting them through the unbot addon this doesn`t happen.

**Commit hash**
2e37c1ff1d7f (Playerbot Branch)

**To Reproduce**
1. Go to camp narache with bots active
2. Invite 1 or more bots to follow you
3. Go to Bramblebade Ravine
4. Kill mobs there

**Screenshots**
![Screenshot 2024-11-06 174458](https://github.com/user-attachments/assets/4e914059-29ea-49ce-b56a-e67a719989c7)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by dedahr** [comment]
Dunno if it's related, but I had similar behaviour and cause was Carbonite and it's quest status chat spam (somehow bots reacted to that because of Quest items in Carbonite txt). After I turned off quest status announcement all was ok.

Actally I turned off all Carbonite chatter/announcements to channels and after that bots stop trading like madmans.

**Comment by AldebaraanMKII** [comment]
> Dunno if it's related, but I had similar behaviour and cause was Carbonite and it's quest status chat spam (somehow bots reacted to that because of Quest items in Carbonite txt). After I turned off quest status announcement all was ok.
> 
> Actally I turned off all Carbonite chatter/announcements to channels and after that bots stop trading like madmans.

Yeah that seems to fix it.
