### ISSUE TITLE
Module Maintainer Status

### ISSUE THREAD

**Issue by ZhengPeiRu21** [liyunfan1223/mod-playerbots#7]
你好，感谢你在Playerbots上的出色表现！你做的改动质量很高，修复了许多长期存在的问题。抱歉通过GitHub issue联系你，因为不知道你其他的联系方式。你是否愿意被添加为Playerbots module repo的maintainer呢？我正在将你的更新合并到parent repo，将你添加为maintainer后，你可以直接在module里做改动。如果你更愿意继续在自己的fork上做修复，也没问题！

**Comment by liyunfan1223** [comment]
首先感谢你维护的mod源码。关于后续的维护，可以把我添加为原仓库maintainer，我后续可以把部分更新用pull request的方式合入。

**Comment by garfieldz90** [comment]
感谢你的更新，真的让mod大幅度提高！

**Comment by liyunfan1223** [comment]
First of all, thank you again for your maintenance of the mod! I very much agree with your statement. At present, players are divided into different communities and lack sufficient communication, which is not good for the development of the project. I will migrate the update to the original mod later, and continue to update on it. 

At the same time, I want to know what I need to pay attention to when maintaining on the original repo, because it involves multi-person collaboration. Frankly maintaining on my fork makes me feel a little freer, but we can also achieve a better development status through further discussions, and even attract more people to participate in the contribution of the project. A lot of work remains to be done, such as dealing with old issues, organizing community discussions and contributions, etc. I hope we can solve these problems together.

**Comment by ZhengPeiRu21** [comment]
Thank you for your kind and prompt response! I completely agree. Please continue to work however you feel most comfortable. I will try my best in the next few days to update the original repo and keep it in sync with your fork in the future.
