### ISSUE TITLE
[BUG]Accept quest and entering the Dungeons to will result in a crash

### ISSUE THREAD

**Issue by moncat2005** [liyunfan1223/mod-playerbots#727]
**Describe the bug**
Accept the quest and enter the dungeon, immediately crash
playerbots logs：
2024-11-18 13:10:09 %-5s [playerbots] Wrong format occurred (argument not found). Fmt string: 'AcceptQuestAction {Inside the Frozen Citadel} - {24506}'

**Commit hash**
AzerothCore rev. fce06946e1b6 2024-11-16 13:15:00 +0800 (Playerbot branch)
 OS: Ubuntu 22.04

**To Reproduce**
1. Horde player acceptQuest (24506) Inside the Frozen Citadel
2. go to Frozen Citadel and Team with playerbots
3. Into Dungeons Forge of Souls 
4. crash

**Comment by serverwar** [comment]
![image](https://github.com/user-attachments/assets/64df08ae-db3e-4b30-a474-84c2db16697c)
It must be an update from them, I don't have this problem, but all the implemented dungeons gave me a headache with crashes.

**Comment by Dreathean** [comment]
Man if you're frustrated with encountering some issues you're more than welcome to stay on an older commit. These are all additions made by talented individuals volunteering their time and effort into this project, and because they are individuals that means they can't necessarily discover every possible problem with each commit. Just because you got crashes doesn't mean they did, which I'm sure you understand.

Perhaps they could wait until more people test it before merging the PR, but honestly there aren't many people that are willing to take the time to test PRs. So it comes down to this until people find issues that can then hopefully be resolved.

As far as all other longer existing issues, sure it would be nice for those to get resolved, but people understandably do what they can based on their expertise and interest. So for me I'm just happy to see more development on this project period.

**Comment by serverwar** [comment]
> Man if you're frustrated with encountering some issues you're more than welcome to stay on an older commit. These are all additions made by talented individuals volunteering their time and effort into this project, and because they are individuals that means they can't necessarily discover every possible problem with each commit. Just because you got crashes doesn't mean they did, which I'm sure you understand.
> 
> Perhaps they could wait until more people test it before merging the PR, but honestly there aren't many people that are willing to take the time to test PRs. So it comes down to this until people find issues that can then hopefully be resolved.
> 
> As far as all other longer existing issues, sure it would be nice for those to get resolved, but people understandably do what they can based on their expertise and interest. So for me I'm just happy to see more development on this project period.


I agree with everything you said, but for a project to have a solid foundation, it needs to fix bugs first and then take the next step. If there are reports of crashes or bugs, fix them, because servers will go down and then after fixing them, add more things. Now, throwing tons of stuff without in-depth testing results in more crashes and whoever downloads it for the first time will have a horrible experience.

**Comment by noisiver** [comment]
You are correct @serverwar but it's not always that simple either. There were tons of crashes related to the server running out of memory. That's not something you can just throw together a fix for but it needs research and decisions on how to fix it. This is much simpler and easier to fix but someone still has to find the cause and decide on how to fix it, not to mention the fact that someone has to actually have time to do it.

Sometimes the best test is to merge it, unfortunately. We don't exactly get a lot of testers that are able to test stuff, and most people don't want to wait for fixes - it's all about fixing things rather than making sure they work, mainly because they aren't fully aware of what can happen.

I do agree with you that it is kind of crucial since it renders the entire instance unplayable, with bots anyway, but there are still more factors to consider.

Also, not all crashes and bugs come from this module or even the changes to the core done for the purpose of supporting this module. I've had plenty of crashes, even client crashes, as a result of changes to AzerothCore.
