### ISSUE TITLE
Scarlet Monastary Library

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#748]
When i finish the Scarlet Monatary the  Library ,  server freese  and then i have to restart the server . 
Happens many times

**Comment by davvvve1** [comment]
Gonna try to set MapUpdate.Threads=1 and ThreadPool=2  and see if its crashing again

**Comment by davvvve1** [comment]
Nope . Still crashes the server

**Comment by davvvve1** [comment]
I noticed that only 3 bots saying goodbye and then the server freese . Tried 3 times and it crashed . My hunter is level 34 .

**Comment by davvvve1** [comment]
Clear all bots and removed druids to spawn . Now i havent got any crashes . I noticed that  when it crashed i had one druid in my team . Or maybe it was something else

**Comment by noisiver** [comment]
It helps if you provide crash logs. Very much so. Without them it's impossible to tell why it crashed and even less how to fix it.

If one can't be provided the issue should be closed until it can.

**Comment by Dreathean** [comment]
Closing due to no crash logs posted as requested after 2 weeks, @davvvve1 if you're still experiencing this problem please post crash logs and add if this is isolated to that instance or if it's more, and what other modules you're using that might be interfering with playerbots as it doesn't seem that anything is experiencing this particular issue.
