### ISSUE TITLE
Why always add all the characters under my account to the team every time I go online

### ISSUE THREAD

**Issue by qyh214** [liyunfan1223/mod-playerbots#750]
**Describe the bug**
go online and choose an char ingame,your account all chars will log in and join your group.

**Commit hash**
https://github.com/liyunfan1223/azerothcore-wotlk/commit/1294d79764e30a2ab7778ef66c07691bb590e702

**To Reproduce**
1. go online
2. choose one char
3. ingame

**Expected behavior**
this feature maybe should can control?(or maybe this already exists, but I couldn't find it?)

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11

**Additional context**
n/a

**Comment by noisiver** [comment]
The two reasons that come to mind begins with this: https://github.com/liyunfan1223/mod-playerbots/blob/3e449fff731fd79bfc1fc5e5f8abd1f23ea81ac8/conf/playerbots.conf.dist#L127
The second reason could be the MultiBot addon but I don't know if you're using it since you never mentioned it and it shouldn't do it if you're not already in a group but I don't know that for sure.

**Comment by qyh214** [comment]
> The two reasons that come to mind begins with this: https://github.com/liyunfan1223/mod-playerbots/blob/3e449fff731fd79bfc1fc5e5f8abd1f23ea81ac8/conf/playerbots.conf.dist#L127
> 
> The second reason could be the MultiBot addon but I don't know if you're using it since you never mentioned it and it shouldn't do it if you're not already in a group but I don't know that for sure.

thanks and I will test it
