### ISSUE TITLE
Playerbots occasionally stuck moving back and forth when deciding to fight a mob

### ISSUE THREAD

**Issue by Dreathean** [liyunfan1223/mod-playerbots#9]
First of all, I just want to say thank you so much for all of the work you're putting into this. I just got the server going with this module and going to find whatever bugs I can. For starters, the Playerbots occasionally get stuck moving back and forth to a mob when deciding to fight it

https://github.com/liyunfan1223/mod-playerbots/assets/132776330/cc65b989-ed1d-47fe-a9e6-114ebc272359

**Comment by liyunfan1223** [comment]
Fixed: https://github.com/liyunfan1223/mod-playerbots/commit/e93b1edcd557c4c0a2aa4de5ffd19b391030e300
Due to some strategy conflicts, this issue would happen to druid and shaman random bots, now it was fixed. 
Thank you for your feedback and detailed description! If you find more issues, welcome to continue to give me feedback.
