### ISSUE TITLE
随机机器人不会自动上坐骑

### ISSUE THREAD

**Issue by bing88868** [liyunfan1223/mod-playerbots#91]
问题：请问我的角色20级学了骑术，随机机器人也学了，但是我上坐骑后，随机机器人不会自动上坐骑，这个正常吗？或者怎么能让随机机器人上坐骑呢？

**Comment by liyunfan1223** [comment]
A random bot that has just been upgraded to level 20 needs to be initialized so that it has a mount. You can use the initialization command `.playerbot rndbot init` in server console to initialize, or wait for a period of time and then automatically initialize (the period is configurable, the default is up to two weeks).
